services:
  web:
    build:
      dockerfile: config/web/Dockerfile
    command: python manage.py runserver --noreload --nostatic 0.0.0.0:8000
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 80:8000
  capture:
    build:
      dockerfile: config/web/Dockerfile
    command: python manage.py capture_data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    devices:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    privileged: true
  publish:
    build:
      dockerfile: config/web/Dockerfile
    command: python manage.py publish_data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - MQTT_BROKER=mqtt
      - POSTGRES_HOST=db
  db:
    image: postgres:15-alpine
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    volumes:
      - /var/lib/solar/postgresql/data:/var/lib/postgresql/data
  mqtt:
    image: eclipse-mosquitto:2
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    ports:
      - 1883:1883
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
