services:
  db:
    image: postgres
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
