services:
  db:
    image: ghcr.io/mateusznowakdev/solar/db:1.7
    build:
      dockerfile: config/db/Dockerfile
    env_file:
      - .env
    volumes:
      - ./config/db/data:/var/lib/postgresql/data
  mqtt:
    image: ghcr.io/mateusznowakdev/solar/mqtt:1.7
    build:
      dockerfile: config/mqtt/Dockerfile
    env_file:
      - .env
    ports:
      - 1883:1883
      - 8883:8883
