services:
  frontend:
    image: ghcr.io/mateusznowakdev/solar/frontend:1.7
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: journald
    ports:
      - 80:80
  backend:
    image: ghcr.io/mateusznowakdev/solar/backend:1.7
    command: python manage.py runserver --noreload --nostatic 0.0.0.0:8000
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    logging:
      driver: journald
    ports:
      - 8000:8000
  communicator:
    image: ghcr.io/mateusznowakdev/solar/backend:1.7
    command: python manage.py run_communicator
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    devices:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - MQTT_BROKER=mqtt
      - POSTGRES_HOST=db
    logging:
      driver: journald
    privileged: true
  transformer:
    image: ghcr.io/mateusznowakdev/solar/backend:1.7
    command: python manage.py run_transformer
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    logging:
      driver: journald
  db:
    image: postgres:15.6-alpine3.19
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    logging:
      driver: journald
    volumes:
      - /var/lib/solar/postgresql/data:/var/lib/postgresql/data
  mqtt:
    image: ghcr.io/mateusznowakdev/solar/mqtt:1.7
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: journald
    ports:
      - 1883:1883
      - 8883:8883
