services:
  frontend:
    build:
      dockerfile: config/frontend/Dockerfile
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: journald
    ports:
      - 80:80
  backend:
    build:
      dockerfile: config/backend/Dockerfile
    command: python manage.py runserver --noreload --nostatic 0.0.0.0:8000
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    logging:
      driver: journald
    ports:
      - 8000:8000
  tasks:
    build:
      dockerfile: config/backend/Dockerfile
    command: python manage.py run_tasks
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    devices:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - MQTT_BROKER=mqtt
      - POSTGRES_HOST=db
    logging:
      driver: journald
    privileged: true
  db:
    image: postgres:15-alpine
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    logging:
      driver: journald
    volumes:
      - /var/lib/solar/postgresql/data:/var/lib/postgresql/data
  mqtt:
    image: eclipse-mosquitto:2
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: journald
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
