services:
  frontend:
    image: ghcr.io/mateusznowakdev/solar/frontend:1.7
    # THIS IMAGE SHOULD BE DOWNLOADED FROM THE REGISTRY
    # build:
    #   dockerfile: config/frontend/Dockerfile
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: journald
  backend:
    image: ghcr.io/mateusznowakdev/solar/backend:1.7
    # THIS IMAGE SHOULD BE DOWNLOADED FROM THE REGISTRY
    # build:
    #   dockerfile: config/backend/Dockerfile
    command: python manage.py runserver --noreload --nostatic 0.0.0.0:8000
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    logging:
      driver: journald
    ports:
      - 8000:8000
  communicator:
    image: ghcr.io/mateusznowakdev/solar/backend:1.7
    # THIS IMAGE SHOULD BE DOWNLOADED FROM THE REGISTRY
    # build:
    #   dockerfile: config/backend/Dockerfile
    command: python manage.py run_communicator
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    devices:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - MQTT_BROKER=mqtt
      - POSTGRES_HOST=db
    logging:
      driver: journald
    privileged: true
  transformer:
    image: ghcr.io/mateusznowakdev/solar/backend:1.7
    # THIS IMAGE SHOULD BE DOWNLOADED FROM THE REGISTRY
    # build:
    #   dockerfile: config/backend/Dockerfile
    command: python manage.py run_transformer
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    logging:
      driver: journald
  db:
    image: ghcr.io/mateusznowakdev/solar/db:1.7
    build:
      dockerfile: config/db/Dockerfile
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    logging:
      driver: journald
    volumes:
      - /var/lib/solar/postgresql/data:/var/lib/postgresql/data
  mqtt:
    image: ghcr.io/mateusznowakdev/solar/mqtt:1.7
    build:
      dockerfile: config/mqtt/Dockerfile
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: journald
    ports:
      - 1883:1883
      - 8883:8883
  nginx:
    image: ghcr.io/mateusznowakdev/solar/nginx:1.7
    build:
      dockerfile: config/nginx/Dockerfile
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: journald
    ports:
      - 80:80
