services:
  db:
    image: postgres:15.6-alpine3.19
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./config/db/data:/var/lib/postgresql/data
  mqtt:
    build:
      dockerfile: config/mqtt/Dockerfile
    env_file:
      - .env
    ports:
      - 1883:1883
      - 8883:8883
