services:
  web:
    build: .
    command: python manage.py runserver --noreload --nostatic
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
  capture:
    build: .
    command: python manage.py capture_data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    devices:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    privileged: true
  db:
    image: postgres
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
      - .env
    volumes:
      - /var/lib/solar/postgresql/data:/var/lib/postgresql/data
