[tool.poetry]
name = "solar"
version = "1.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.5"
django-cors-headers = "^4.2.0"
djangorestframework = "^3.14.0"
drf-spectacular = "^0.26.4"
paho-mqtt = "^1.6.1"
psycopg = {extras = ["binary"], version = "^3.1.10"}
pymodbus = "^3.5.2"
pyserial = "^3.5"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
isort = "^5.12.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
