[tool.poetry]
name = "solar"
version = "1.4.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.5"
django-cors-headers = "^4.2.0"
djangorestframework = "^3.14.0"
drf-spectacular = "^0.26.5"
paho-mqtt = "^1.6.1"
psycopg = {extras = ["binary"], version = "^3.1.12"}
pymodbus = "^3.5.2"
pyserial = "^3.5"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
isort = "^5.12.0"
pylint = "^3.0.2"
pylint-django = "^2.5.5"

[tool.isort]
profile = "black"

[tool.pylint]
disable = ["broad-exception-raised", "missing-class-docstring", "missing-function-docstring", "missing-module-docstring", "too-few-public-methods"]
django-settings-module = "solar.settings"
ignore = "migrations"
load-plugins = ["pylint_django"]
max-attributes = 10

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
