CHARGE_PRIORITY_ID_PREFER_PV = 0
CHARGE_PRIORITY_ID_PREFER_GRID = 1
CHARGE_PRIORITY_ID_HYBRID = 2
CHARGE_PRIORITY_ID_ONLY_PV = 3

CHARGE_PRIORITY_ALLOWED = (0, 1, 2, 3)

OUTPUT_PRIORITY_ID_PV = 0
OUTPUT_PRIORITY_ID_GRID = 1
OUTPUT_PRIORITY_ID_INVERTER = 2

OUTPUT_PRIORITY_ALLOWED = (0, 1, 2)
