FROM eclipse-mosquitto:2.0.18

COPY config/mqtt/mosquitto.acl /mosquitto/config/mosquitto.acl
COPY config/mqtt/mosquitto.conf /mosquitto/config/mosquitto.conf
COPY config/mqtt/docker-entrypoint.sh /docker-entrypoint.sh
