# Generated by Django 4.2.3 on 2023-08-03 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_charge_power_state_battery_apparent_power"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="current_time",
        ),
    ]
