# Generated by Django 4.2.5 on 2023-11-10 23:31

from django.db import migrations, models


def columns_to_json(apps, schema_editor):
    LogEntry = apps.get_model("core", "LogEntry")

    for entry in LogEntry.objects.all():
        entry.data["event"] = entry.field_name
        entry.data["value"] = entry.new_value
        entry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_statearchive"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.RunPython(columns_to_json),
        migrations.RemoveField(
            model_name="logentry",
            name="field_name",
        ),
        migrations.RemoveField(
            model_name="logentry",
            name="new_value",
        ),
        migrations.RemoveField(
            model_name="logentry",
            name="old_value",
        ),
    ]
