# Generated by Django 4.2.7 on 2023-11-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_logentry_field_name_remove_logentry_new_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingsEntry",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("checked", models.BooleanField()),
            ],
        ),
    ]
