# Generated by Django 5.0.2 on 2024-02-22 19:17

from django.db import migrations


def update_name(apps, schema_editor):
    LogEntry = apps.get_model("core", "LogEntry")

    for entry in LogEntry.objects.all():
        if entry.name == "inverter_connected":
            entry.name = "system_connecting"
            entry.save()
        elif entry.name == "auto_charge_priority_changed":
            entry.name = "system_charge_priority"
            entry.save()
        elif entry.name == "auto_output_priority_changed":
            entry.name = "system_output_priority"
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_logentry_data_logentry_category_logentry_name_and_more"),
    ]

    operations = [
        migrations.RunPython(update_name),
    ]
