# Generated by Django 4.2.3 on 2023-07-30 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_state_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state",
            old_name="charge_power",
            new_name="battery_apparent_power",
        ),
    ]
