# Generated by Django 4.2.4 on 2023-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_state_current_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("field_name", models.CharField(max_length=50)),
                ("old_value", models.FloatField()),
                ("new_value", models.FloatField()),
            ],
        ),
    ]
