# Generated by Django 4.2.4 on 2023-08-23 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_statecache_remove_logentry_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="State",
            new_name="StateRaw",
        ),
    ]
