on:
  push:
    tags:
      - "1.9.0"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - image: backend
            file: config/backend/Dockerfile
          - image: frontend
            file: config/frontend/Dockerfile
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - uses: docker/setup-qemu-action@v3
        id: qemu
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - uses: docker/login-action@v3
        id: login
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}
      - uses: docker/build-push-action@v5
        id: build
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.file }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
